server:
  port: 8081
spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
  shell:
    interactive:
      enabled: true

application:
  countQuestionForPass: 3
  locale: en
  localizationFile:  "/questionsEn.csv"


#https://involta.ru/tools/decoder/