spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  countQuestionForPass: 3
  locale: en
  engLocalizationFile:  "/questionsEn.csv"
  ruLocalizationFile: "/questionsRu.csv"


#https://involta.ru/tools/decoder/